# .air.toml

# Config file for Air (https://github.com/air-verse/air)

[build]
# Command to build the binary
cmd = "go build -o ./tmp/main cmd/main.go"
# Binary output
bin = "./tmp/main"
# Command to run the binary
full_bin = "APP_ENV=dev ./tmp/main"
# Watch patterns
include_ext = ["go", "tpl", "tmpl", "html"]

[directories]
# Watch these directories
watch_dir = ["./"]

[logger]
# Enable colorful logs
color = true
# Enable timestamps in logs
timestamp = false
